import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins, } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger, SidebarInset, Sidebar } from "@/components/ui/sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import 'primereact/resources/themes/lara-light-cyan/theme.css'; // Theme
import 'primereact/resources/primereact.min.css';                // Core CSS
import 'primeicons/primeicons.css';      
import { Toaster } from 'sonner';


 


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // Pilih weight yang dibutuhkan
  variable: '--font-poppins',
})
const Sans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TeknoSea Weather Monitoring",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Pliant:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
      </head>
      <body suppressHydrationWarning={true} className={`${poppins.variable} font-sans`}>
         <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
        <main className="flex flex-1 flex-col">
        {children}

         <Toaster />
      </main>
        </ThemeProvider>
     </body>
   </html>
  );
}
